site_name: 'JumpServer 文档'
site_url: 'https://docs.jumpserver.org'
site_author: 'jumpserver'
site_description: "JumpServer 开源堡垒机的在线文档"

repo_name: 'jumpserver/jumpserver'
repo_url: 'https://github.com/jumpserver/jumpserver'
edit_uri: ''

theme:
  name: 'material'
  logo: 'img/logo.png'
  favicon: 'img/facio.ico'
  language: 'zh'
  palette:
    - scheme: default
      accent: 'red'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      accent: 'red'
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
  font: false
  custom_dir: 'theme'
  icon:
    repo: fontawesome/brands/github

nav:
  - 产品介绍: index.md
  - 快速入门: quick_start.md
  - 系统架构: architecture.md
  - 安装部署:
    - Linux 单机部署:
        - 环境要求: jms_install/linux_stand-alone/requirements.md
        - 在线安装: jms_install/linux_stand-alone/on_line_install.md
        - 离线安装: jms_install/linux_stand-alone/off_line_install.md
        - 在线升级: jms_install/linux_stand-alone/on_line_upgrade.md
        - 离线升级: jms_install/linux_stand-alone/off_line_upgrade.md
    - Linux 集群模式部署:
        - 准备工作: jms_install/linux_lb/requirements.md
        - 部署 NFS 服务: jms_install/linux_lb/nfs_install.md
        - 部署 MySQL 服务: jms_install/linux_lb/mysql_install.md
        - 部署 Redis 服务: jms_install/linux_lb/redis_install.md
        - 部署 JumpServer 01 节点: jms_install/linux_lb/jms_install_node01.md
        - 部署 JumpServer 02 节点: jms_install/linux_lb/jms_install_node02.md
        - 部署 JumpServer 03 节点: jms_install/linux_lb/jms_install_node03.md
        - 部署 JumpServer 04 节点: jms_install/linux_lb/jms_install_node04.md
        - 部署 HAProxy 服务: jms_install/linux_lb/haproxy_install.md
        - 部署 MinIO 服务: jms_install/linux_lb/minio_install.md
        - 部署 Elasticsearch 服务: jms_install/linux_lb/elasticsearch_install.md
        - 注意事项: jms_install/linux_lb/linux_lb_upgrade.md
    - Kubernetes  Helm 模式部署:
        - 在线安装: jms_install/k8s_helm/helm_on_line_install.md
        - 在线升级: jms_install/k8s_helm/helm_on_line_upgrade.md
    - 源码部署:
        - 环境说明: jms_install/source_install/requirements.md
        - Core 环境部署: jms_install/source_install/core_install.md
        - Lina 环境部署: jms_install/source_install/lina_install.md
        - Luna 环境部署: jms_install/source_install/luna_install.md
        - KoKo 环境部署: jms_install/source_install/koko_install.md
        - Lion 环境部署: jms_install/source_install/lion_install.md
        - Magnus 环境部署: jms_install/source_install/magnus_install.md
        - Nginx 环境部署: jms_install/source_install/nginx_install.md
        - JumpServer 环境整合: jms_install/source_install/merge_jumpserver.md
    - 迁移文档: jms_install/migration.md
    - 升级须知: jms_install/upgrade_notice.md
    - 国密改造: jms_install/gmssl.md
    - 反向代理: jms_install/proxy.md
    - 资源下载: jms_install/download.md
    - 命令行工具: jms_install/jmsctl_sh.md
    - 数据库加密连接:
        - 数据库 SSL 连接: jms_install/db_ssl/mysql_ssl.md
        - Redis SSL 连接: jms_install/db_ssl/redis_ssl.md
  - 功能手册:
    - 页面说明: guide/index_description.md
    - 通用功能: guide/currency.md
    - 资产要求:
        - Telnet: guide/asset_requirements/telnet.md
        - Linux SSH: guide/asset_requirements/linux_ssh.md
        - Linux VNC: guide/asset_requirements/linux_vnc.md
        - macOS VNC: guide/asset_requirements/macos_vnc.md
        - Windows SSH: guide/asset_requirements/windows_ssh.md
        - Windows VNC: guide/asset_requirements/windows_vnc.md
        - Windows RDP: guide/asset_requirements/windows_rdp.md
        - MySQL: guide/asset_requirements/mysql.md
        - Kubernetes: guide/asset_requirements/kubernetes.md
    - 管理手册:
        - 仪表盘: guide/admin/dashboard.md
        - 用户管理:
            - 用户列表: guide/admin/user/user_list.md
            - 用户组: guide/admin/user/user_group.md
            - 角色列表: guide/admin/user/role_list.md
        - 资产管理:
            - 资产列表: guide/admin/asset/asset_list.md
            - 网域列表: guide/admin/asset/domain_list.md
            - 平台列表: guide/admin/asset/platform_list.md
            - 标签列表: guide/admin/asset/lable_list.md
        - 账号管理:
            - 账号列表: guide/admin/account/account_list.md
            - 账号模版: guide/admin/account/account_template.md
            - 账号推送: guide/admin/account/account_push.md
            - 账号收集 (X-Pack): guide/admin/account/account_collect.md
            - 账号改密 (X-Pack): guide/admin/account/account_densification.md
            - 账号备份 (X-Pack): guide/admin/account/account_backup.md
        - 权限管理:
            - 资产授权: guide/admin/permission/asset_authorization.md
            - 资产登陆 (X-Pack): guide/admin/permission/asset_login.md
            - 命令过滤: guide/admin/permission/command_filter.md
        - 任务中心:
            - 任务列表: guide/admin/task/task_list.md
            - 任务监控: guide/admin/task/task_monitor.md
        - 工单 (X-Pack): guide/admin/admin_work_order.md
    - 审计手册:
        - 仪表盘: guide/audit/dashboard.md
        - 会话审计:
            - 会话记录: guide/audit/session_audit/session_record.md
            - 命令记录: guide/audit/session_audit/command_record.md
            - 文件传输: guide/audit/session_audit/file_transfer.md
        - 日志审计:
            - 登录日志: guide/audit/log_audit/login_log.md
            - 操作日志: guide/audit/log_audit/operation_log.md
            - 改密日志: guide/audit/log_audit/densification_log.md
            - 作业日志: guide/audit/log_audit/job_log.md
    - 用户手册:
        - 概览页: guide/user/index_overview.md
        - 个人信息:
            - 账号信息: guide/user/personal_information/account_information.md
            - 个人信息: guide/user/personal_information/personal_information.md
            - 连接令牌: guide/user/personal_information/connect_token.md
        - 我的资产: guide/user/my_asset.md
        - Web 终端: guide/user/web_terminal.md
        - 文件管理: guide/user/file_management.md
        - 作业中心:
            - 快捷命令: guide/user/job/quick_command.md
            - 作业管理: guide/user/job/job_management.md
            - 模版管理: guide/user/job/template_management.md
            - 执行历史: guide/user/job/execution_history.md
        - 工单 (X-Pack): guide/user/user_work_order.md
    - 系统设置:
        - 概览页: guide/system/index_overview.md
        - 基本设置: guide/system/basic.md
        - 邮件设置: guide/system/email.md
        - 认证设置:
            - MFA: guide/system/authentication/mfa.md
            - OpenID: guide/system/authentication/openid.md
            - SSO (X-Pack): guide/system/authentication/sso.md
            - CAS (X-Pack): guide/system/authentication/cas.md
            - LDAP (X-Pack): guide/system/authentication/ldap.md
            - SAML2 (X-Pack): guide/system/authentication/saml2.md
            - Radius (X-Pack): guide/system/authentication/radius.md
            - 钉钉 (X-Pack): guide/system/authentication/dingtalk.md
            - 微信 (X-Pack): guide/system/authentication/wechat.md
            - 飞书 (X-Pack): guide/system/authentication/feishu.md
        - 消息订阅: guide/system/message.md
        - 短信设置 (X-Pack): guide/system/sms.md
        - 终端设置: guide/system/terminal.md
        - 远程应用 (X-Pack): guide/system/remoteapp.md
        - 安全设置: guide/system/security.md
        - 定期清理: guide/system/regular_clean.md
        - 界面设置 (X-Pack): guide/system/index_logo.md
        - 组织管理 (X-Pack): guide/system/organization.md
        - 其他设置: guide/system/othen.md
        - 系统工具: guide/system/telnet_ping.md
    - 参数说明: guide/env.md
    - 存储说明: guide/storages.md
  - 最佳实践: best_practices.md
  - 常见问题:
    - 产品 FAQ: faq/faq.md
    - 安全建议: faq/security.md
    - 企业版: faq/enterprise.md
  - 开发文档:
    - API 文档: dev/rest_api.md
    - 交互命令: dev/shell.md
  - 用户案例: user_stories.md
  - 更新日志: change_log.md
  - 技术咨询: https://jinshuju.net/f/sQ91MK
  - 联系我们: contact.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ⚓︎
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - theme/.icons
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.saneheaders
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  jumpserver:
    version: v3.0.0
    jmservisor: v1.2.5
    wisp: v0.1.6
  installer:
    version: 236
  search:
    separator: '[\s\-\.]+'
    language: 'zh'
    Content-Encoding: gzip
    boost: 100
  generator: false
  version:
    default: master
    provider: mike
  analytics:
    provider: google
    property: UA-147297392-3
  social:
    - icon: Bilibili_Logo_Blue
      link: https://www.bilibili.com/video/BV19D4y1S7s4
    - icon: fontawesome/brands/github
      link: https://github.com/jumpserver
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/jumpserver/
    - icon: fontawesome/solid/envelope
      link: mailto:support@fit2cloud.com
    - icon: fontawesome/brands/skype
      link: tel://400-052-0755
    - icon: fontawesome/brands/qq
      link: https://qm.qq.com/cgi-bin/qm/qr?k=om7dOmqflNsfzegPBODIxooO_dMDGiD1&jump_from=webapi

extra_css:
  - css/extra.css
  - css/termynal.css
  - css/custom.css
  - stylesheets/extra.css

extra_javascript:
  - js/termynal.js
  - js/custom.js

copyright: Copyright &copy; 2014-2023 <a href="https://www.fit2cloud.com">杭州飞致云信息科技有限公司</a>, All Rights Reserved. <a href="http://www.beian.miit.gov.cn" target="_blank">京ICP备15023818号</a>
plugins:
    - search:
        lang:
          - en
          - ja
        separator: '[\s\-\.]+'
    - macros
