site_name: 'JumpServer 文档'
site_url: 'https://docs.jumpserver.org'
site_author: 'wojiushixiaobai'
site_description: "JumpServer 是全球首款开源的堡垒机"

repo_name: 'jumpserver/jumpserver'
repo_url: 'https://github.com/jumpserver/jumpserver'
edit_uri: ''

theme:
  name: 'material'
  logo: 'img/logo.png'
  favicon: 'img/facio.ico'
  language: 'zh'
  palette:
    - scheme: default
      accent: 'red'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      accent: 'red'
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
  font: false
  custom_dir: 'theme'
  icon:
    repo: fontawesome/brands/github

nav:
#  - 总体介绍: index.md
#  - 安装配置:
#    - 安装部署: install/setup_by_fast.md
#    - 负载均衡: install/setup_by_lb.md
#    - 升级文档: install/upgrade/upgrade.md
#    - 迁移文档: install/migration.md
#    - 安全建议: install/install_security.md
#  - 管理文档:
#   - 快速入门: admin-guide/quick_start.md
#   - 资产要求:
#       - Telnet: admin-guide/assets/telnet.md
#        - Linux SSH: admin-guide/assets/linux_ssh.md
#        - Linux VNC: admin-guide/assets/linux_vnc.md
#        - macOS VNC: admin-guide/assets/macos_vnc.md
#        - Windows SSH: admin-guide/assets/windows_ssh.md
#        - Windows VNC: admin-guide/assets/windows_vnc.md
#        - Windows RDP: admin-guide/assets/windows_rdp.md
#    - 应用要求:
#        - MySQL: admin-guide/app/mysql.md
#        - Kubernetes: admin-guide/app/kubernetes.md
#    - 身份认证:
#        - SSO: admin-guide/authentication/sso.md
#        - CAS: admin-guide/authentication/cas.md
#        - MFA: admin-guide/authentication/mfa.md
#        - LDAP: admin-guide/authentication/ldap.md
#        - SAML2: admin-guide/authentication/saml2.md
#        - OpenID: admin-guide/authentication/openid.md
#        - Radius: admin-guide/authentication/radius.md
#        - 钉钉: admin-guide/authentication/dingtalk.md
#        - 微信: admin-guide/authentication/wechat.md
#        - 飞书: admin-guide/authentication/feishu.md
#    - 反向代理: admin-guide/proxy.md
#    - 国密改造: admin-guide/gmssl.md
#    - 参数说明: admin-guide/env.md
#    - 存储说明: admin-guide/storages.md
#  - 开发文档:
#    - API 文档: dev/rest_api.md
#    - 编译文档: dev/build.md
#    - 交互命令: dev/shell.md
#  - 用户文档:
#    - 个人页面:
#      - 首次登录: user-guide/login/login-first.md
#      - 概览页面: user-guide/login/dashboard.md
#      - 个人信息: user-guide/users/profile.md
#    - 终端登录: user-guide/login/terminal-login-SSH.md
#    - 我的资产: user-guide/assets/user-asset.md
#    - 我的应用:
#      - 远程应用: user-guide/apps/user-remoteapp.md
#      - 数据库: user-guide/apps/user-database.md
#      - Kubernetes: user-guide/apps/user-kubernetes.md
#    - 批量命令: user-guide/ops/command-executions/create.md
#    - Web 终端:
#      - 主题设置: user-guide/terminal/web-terminal-theme.md
#      - 会话分享: user-guide/terminal/web-terminal-share.md
#      - 文件管理:
#        - SSH 协议: user-guide/terminal/filemanagement/ssh/filemanagement.md
#        - RDP 协议: user-guide/terminal/filemanagement/rdp/webgui.md
#      - 设置: user-guide/terminal/web-terminal-config.md
#    - 文件管理: user-guide/terminal/filemanagement/ssh/filemanagement.md
#  - 帮助文档:
#    - 升级问题: faq/upgrade.md
#    - 组件问题: faq/other.md
#    - 资源下载: about/download.md
#  - 更新说明: https://github.com/jumpserver/jumpserver/releases
#  - 关于我们:
#    - 贡献列表: about/contributor.md
#    - 联系方式: about/contact.md
#    - 技术咨询: https://jinshuju.net/f/sQ91MK
#  - 20230207: index.md
  - 产品介绍: 01_primary_directory/index.md
  - 快速入门: 01_primary_directory/quickstart.md
  - 系统架构: 01_primary_directory/architecture.md
  - 安装部署:
    - Linux 单机部署: 
        - 环境要求: 02_jms_install/linux_stand-alone/requirements.md
        - 在线安装: 02_jms_install/linux_stand-alone/on_line_install.md
        - 离线安装: 02_jms_install/linux_stand-alone/off_line_install.md
        - 在线升级: 02_jms_install/linux_stand-alone/on_line_upgrade.md
        - 离线升级: 02_jms_install/linux_stand-alone/off_line_upgrade.md
    - Linux LB 模式部署: 
        - 准备工作: 02_jms_install/linux_lb/requirements.md
        - 部署 NFS 服务: 02_jms_install/linux_lb/nfs_install.md
        - 部署 MySQL 服务: 02_jms_install/linux_lb/mysql_install.md
        - 部署 Redis 服务: 02_jms_install/linux_lb/redis_install.md
        - 部署 JumpServer 01 节点: 02_jms_install/linux_lb/jms_install_node01.md
        - 部署 JumpServer 02 节点: 02_jms_install/linux_lb/jms_install_node02.md
        - 部署 JumpServer 03 节点: 02_jms_install/linux_lb/jms_install_node03.md
        - 部署 JumpServer 04 节点: 02_jms_install/linux_lb/jms_install_node04.md
        - 部署 HAProxy 服务: 02_jms_install/linux_lb/haproxy_install.md
        - 部署 MinIO 服务: 02_jms_install/linux_lb/minio_install.md
        - 部署 Elasticsearch 服务: 02_jms_install/linux_lb/elasticsearch_install.md
        - 注意事项: 02_jms_install/linux_lb/linux_lb_upgrade.md
    - Docker Allinone 模式部署: 
        - 快速启动: 02_jms_install/docker_allinone/quick_start.md
        - 标准启动: 02_jms_install/docker_allinone/standard_start.md
        - 升级操作: 02_jms_install/docker_allinone/allinone_upgrade.md
    - Kubernetes  Helm 模式部署: 
        - 在线安装: 02_jms_install/k8s_helm/helm_on_line_install.md
      #  - 离线安装: 02_jms_install/k8s_helm/helm_off_line_install.md
        - 在线升级: 02_jms_install/k8s_helm/helm_on_line_upgrade.md
      #  - 离线升级: 02_jms_install/k8s_helm/helm_off_line_upgrade.md
    # - Pc 端环境部署: 
    #    - Windows 单机部署: 02_jms_install/pc_install/win_install.md
    #    - Mac 单机部署: 02_jms_install/pc_install/mac_install.md
    #    - 环境升级: 02_jms_install/pc_install/pc_upgrade.md
    - 源码部署: 
        - 环境说明: 02_jms_install/source_install/requirements.md
        - Core 环境部署: 02_jms_install/source_install/core_install.md
        - Lina 环境部署: 02_jms_install/source_install/lina_install.md
        - Luna 环境部署: 02_jms_install/source_install/luna_install.md
        - KoKo 环境部署: 02_jms_install/source_install/koko_install.md
        - Lion 环境部署: 02_jms_install/source_install/lion_install.md
        - Magnus 环境部署: 02_jms_install/source_install/magnus_install.md
        - Nginx 环境部署: 02_jms_install/source_install/nginx_install.md
        - JumpServer 环境整合: 02_jms_install/source_install/merge_jumpserver.md
    - 迁移文档: 02_jms_install/migration.md
    - 升级须知: 02_jms_install/upgrade_notice.md
    - 国密改造: 02_jms_install/gmssl.md
    - 反向代理: 02_jms_install/proxy.md
    - 资源下载: 02_jms_install/download.md
    - 命令行工具: 02_jms_install/jmsctl_sh.md
    - 数据库加密连接: 
        - 数据库 SSL 连接: 02_jms_install/db_ssl/mysql_ssl.md
        - Redis SSL 连接: 02_jms_install/db_ssl/redis_ssl.md
  - 功能手册:
    - 页面说明: 03_guide/index_description.md
    - 通用功能: admin-guide/assets/telnet.md
    - 资产要求:
        - Telnet: 03_guide/asset_requirements/telnet.md
        - Linux SSH: 03_guide/asset_requirements/linux_ssh.md
        - Linux VNC: 03_guide/asset_requirements/linux_vnc.md
        - macOS VNC: 03_guide/asset_requirements/macos_vnc.md
        - Windows SSH: 03_guide/asset_requirements/windows_ssh.md
        - Windows VNC: 03_guide/asset_requirements/windows_vnc.md
        - Windows RDP: 03_guide/asset_requirements/windows_rdp.md
        - MySQL: 03_guide/asset_requirements/mysql.md
        - Kubernetes: 03_guide/asset_requirements/kubernetes.md
    - 管理手册:
        - 仪表盘: 03_guide/admin/dashboard.md
        - 用户管理: 
            - 用户列表: 03_guide/admin/user/user_list.md
            - 用户组: 03_guide/admin/user/user_group.md
            - 角色列表: 03_guide/admin/user/role_list.md
        - 资产管理: 
            - 资产列表: 03_guide/admin/asset/asset_list.md
            - 网域列表: 03_guide/admin/asset/domain_list.md
            - 平台列表: 03_guide/admin/asset/platform_list.md
            - 标签列表: 03_guide/admin/asset/lable_list.md
        - 账号管理: 
            - 账号列表: 03_guide/admin/account/account_list.md
            - 账号模版: 03_guide/admin/account/account_template.md
            - 账号推送: 03_guide/admin/account/account_push.md
            - 账号收集: 03_guide/admin/account/account_collect.md
            - 账号改密: 03_guide/admin/account/account_densification.md
            - 账号备份: 03_guide/admin/account/account_backup.md
        - 权限管理:
            - 资产授权: 03_guide/admin/permission/asset_authorization.md
            - 资产登陆: 03_guide/admin/permission/asset_login.md
            - 命令过滤: 03_guide/admin/permission/command_filter.md
        - 任务中心: 
            - 任务列表: 03_guide/admin/task/task_list.md
            - 任务监控: 03_guide/admin/task/task_monitor.md
    - 审计手册: 
        - 仪表盘: 03_guide/audit/dashboard.md
        - 会话审计: 
            - 会话记录: 03_guide/audit/session_audit/session_record.md
            - 命令记录: 03_guide/audit/session_audit/command_record.md
            - 文件传输: 03_guide/audit/session_audit/file_transfer.md
        - 日志审计: 
            - 登录日志: 03_guide/audit/log_audit/login_log.md
            - 操作日志: 03_guide/audit/log_audit/operation_log.md
            - 改密日志: 03_guide/audit/log_audit/densification_log.md
            - 作业日志: 03_guide/audit/log_audit/job_log.md
    - 用户手册: 
        - 概览页: 03_guide/user/index_overview.md
        - 个人信息:
            - 账号信息: 03_guide/user/personal_information/account_information.md
            - 个人信息: 03_guide/user/personal_information/personal_information.md
            - 临时密码: 03_guide/user/personal_information/temporary_passwd.md
            - 连接令牌: 03_guide/user/personal_information/connect_token.md
        - 我的资产: 03_guide/user/my_asset.md
        - Web 终端: 03_guide/user/web_terminal.md
        - 文件管理: 03_guide/user/file_management.md
        - 作业中心:
            - 快捷命令: 03_guide/user/job/quick_command.md
            - 作业管理: 03_guide/user/job/job_management.md
            - 模版管理: 03_guide/user/job/template_management.md
            - 执行历史: 03_guide/user/job/execution_history.md
    - 系统设置: 
        - 概览页: 03_guide/system/index_overview.md
        - 基本设置: 03_guide/system/basic.md
        - 邮件设置: 03_guide/system/email.md
        - 认证设置: 
            - SSO: 03_guide/system/authentication/sso.md
            - CAS: 03_guide/system/authentication/cas.md
            - MFA: 03_guide/system/authentication/mfa.md
            - LDAP: 03_guide/system/authentication/ldap.md
            - SAML2: 03_guide/system/authentication/saml2.md
            - OpenID: 03_guide/system/authentication/openid.md
            - Radius: 03_guide/system/authentication/radius.md
            - 钉钉: 03_guide/system/authentication/dingtalk.md
            - 微信: 03_guide/system/authentication/wechat.md
            - 飞书: 03_guide/system/authentication/feishu.md
        - 消息订阅: 03_guide/system/message.md
        - 短信设置: 03_guide/system/sms.md
        - 终端设置: 03_guide/system/terminal.md
        - 远程应用: 03_guide/system/remoteapp.md
        - 安全设置: 03_guide/system/security.md
        - 定期清理: 03_guide/system/regular_clean.md
        - 界面设置: 03_guide/system/index_logo.md
        - 组织管理: 03_guide/system/organization.md
        - 其他设置: 03_guide/system/othen.md
        - 系统工具: 03_guide/system/telnet_ping.md
        # - 许可证: 
        - 工单: 03_guide/system/work_order.md
    - 参数说明: 03_guide/env.md
    - 存储说明: 03_guide/storages.md
  - 最佳实践: 01_primary_directory/best_practices.md
  - 教学视频: 01_primary_directory/teaching_video.md
  - 常见问题: 
    - 产品 FAQ: 04_faq/faq.md
    - 安全建议: 04_faq/security.md
    - 企业版: 04_faq/enterprise.md 
  - 开发文档:
    - API 文档: 05_dev/rest_api.md
    - 交互命令: 05_dev/shell.md
    # - 开发过程实践: dev/shell.md
  - 用户案例: 01_primary_directory/user_stories.md
  - 更新日志: 06_changelog/change_log.md
  - 技术咨询: https://jinshuju.net/f/sQ91MK
  - 关于我们:
    - 贡献者名单: 07_about_us/contributor.md
    - 联系我们: 07_about_us/contact.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ⚓︎
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - theme/.icons
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.saneheaders
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  jumpserver:
    version: v2.28.6
    jmservisor: v1.2.5
    wisp: v0.0.10
  installer:
    version: 179
  search:
    separator: '[\s\-\.]+'
    language: 'zh'
    Content-Encoding: gzip
    boost: 100
  generator: false
  version:
    default: master
    provider: mike
  analytics:
    provider: google
    property: UA-147297392-3
  social:
    - icon: Bilibili_Logo_Blue
      link: https://www.bilibili.com/video/BV19D4y1S7s4
    - icon: fontawesome/brands/github
      link: https://github.com/jumpserver
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/jumpserver/
    - icon: fontawesome/solid/envelope
      link: mailto:support@fit2cloud.com
    - icon: fontawesome/brands/skype
      link: tel://400-052-0755
    - icon: fontawesome/brands/qq
      link: https://qm.qq.com/cgi-bin/qm/qr?k=om7dOmqflNsfzegPBODIxooO_dMDGiD1&jump_from=webapi

extra_css:
  - css/extra.css
  - css/termynal.css
  - css/custom.css
  - stylesheets/extra.css

extra_javascript:
  - js/termynal.js
  - js/custom.js

copyright: Copyright &copy; 2014-2023 <a href="https://www.fit2cloud.com">杭州飞致云信息科技有限公司</a>, All Rights Reserved. <a href="http://www.beian.miit.gov.cn" target="_blank">京ICP备15023818号</a>
plugins:
    - search:
        lang:
          - en
          - ja
        separator: '[\s\-\.]+'
    - macros
